from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import BookList, BookViewSet

# Create a router
router = DefaultRouter()
router.register(r'books_all', BookViewSet, basename='book_all')

urlpatterns = [
    # Route for ListAPIView (BookList)
    path('books/', BookList.as_view(), name='book-list'),

    # Routes generated by the router for CRUD
    path('', include(router.urls)),
]
